# Generated by Django 5.2.14 on 2026-05-07 15:56

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('unit', models.CharField(choices=[('METER', 'Meter'), ('UNIT', 'Unit'), ('GRAM', 'Gram'), ('SPOOL', 'Spool')], max_length=10, verbose_name='Unit')),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock quantity')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per unit')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Order date')),
                ('due_date', models.DateField(db_index=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PRODUCTION', 'In production'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(choices=[('DRESS', 'Dress'), ('SUIT', 'Suit'), ('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('SKIRT', 'Skirt'), ('ALTERATION', 'Alteration'), ('OTHER', 'Other')], max_length=20, verbose_name='Garment type')),
                ('description', models.TextField(verbose_name='Description')),
                ('fabric', models.CharField(blank=True, max_length=120, verbose_name='Fabric')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='Color')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('design_notes', models.TextField(blank=True, verbose_name='Design notes')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order line',
                'verbose_name_plural': 'Order lines',
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BUST', 'Bust'), ('WAIST', 'Waist'), ('HIPS', 'Hips'), ('INSEAM', 'Inseam'), ('SLEEVE', 'Sleeve'), ('SHOULDER', 'Shoulder'), ('NECK', 'Neck'), ('LENGTH', 'Length'), ('OTHER', 'Other')], max_length=20, verbose_name='Measurement')),
                ('value_cm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Value (cm)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='orders.orderitem', verbose_name='Order line')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='OrderItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity used')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_links', to='orders.material', verbose_name='Material')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_links', to='orders.orderitem', verbose_name='Order line')),
            ],
            options={
                'verbose_name': 'Line material',
                'verbose_name_plural': 'Line materials',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('order_date'))), name='order_due_on_or_after_order_date'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='unique_order_line_position'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('order_item', 'name'), name='unique_measurement_per_line_and_type'),
        ),
        migrations.AddConstraint(
            model_name='orderitemmaterial',
            constraint=models.UniqueConstraint(fields=('order_item', 'material'), name='unique_material_per_order_line'),
        ),
    ]
