# Generated by Django 5.2.14 on 2026-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('COP', 'Colombian peso ($)'), ('USD', 'US dollar ($)')], db_index=True, default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('COP', 'Colombian peso ($)'), ('USD', 'US dollar ($)')], db_index=True, default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
