# Generated by Django 5.2.14 on 2026-05-07 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('sequence', models.PositiveIntegerField(unique=True, verbose_name='Sequence')),
                ('is_terminal', models.BooleanField(db_index=True, default=False, verbose_name='Is terminal')),
            ],
            options={
                'verbose_name': 'Production stage',
                'verbose_name_plural': 'Production stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('TAILOR', 'Tailor'), ('STAFF', 'Staff')], max_length=20, verbose_name='Role')),
                ('hired_on', models.DateField(verbose_name='Hired on')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(db_index=True, verbose_name='Delivered at')),
                ('received_by', models.CharField(max_length=255, verbose_name='Received by')),
                ('final_observations', models.TextField(blank=True, verbose_name='Final observations')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Order')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='production.employee', verbose_name='Delivered by')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], db_index=True, default=2, verbose_name='Priority')),
                ('deadline', models.DateField(blank=True, db_index=True, null=True, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='production.employee', verbose_name='Assigned to')),
                ('current_stage', models.ForeignKey(help_text='Denormalized from latest StatusHistory for fast filtering; kept in sync via signals.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_at_stage', to='production.productionstage', verbose_name='Current stage')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orderitem', verbose_name='Order line')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Changed at')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('allow_backward', models.BooleanField(default=False, help_text='Supervisor override to move to an earlier sequence.', verbose_name='Allow backward move')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='production.employee', verbose_name='Changed by')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='production.productionstage', verbose_name='Stage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='production.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Status history',
                'verbose_name_plural': 'Status history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
